In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
ens = pd.read_excel(r"C:\Users\CEN1\OneDrive - U.S. NRC\CEN1\GAData\ENsRaw.xlsx", index_col=0)

In [3]:
ens.head(20)

,EventNotificationNumber,RevisionNumber,RetractIndicator,SiteName,UnitInd1,UnitInd2,UnitInd3,RxType,NrcNotifiedBy,OperationsOfficer,...,Security,ReleaseDate,Note1,Note2,Note3,ImportedDate,OfInterest,Interest,DocketNumber2,DocketNumber3
EventNotificationId,,,,,,,,,,,,,,,,,,,,,
18700,18715,NaN,0,AREOJET,NaN,NaN,NaN,NaN,WEST (TN),BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18701,18716,NaN,0,FT CALHOUN,1.0,NaN,NaN,[1] CE,BONSALL,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18702,18717,NaN,0,PALISADES,1.0,NaN,NaN,[1] CE,KUBACKI,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18703,18718,NaN,-1,YANKEE ROWE,1.0,NaN,NaN,[1] W-4-LP,JOYCE,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18704,18719,NaN,-1,NORTH ANNA,1.0,2.0,NaN,"[1] W-3-LP,[2] W-3-LP",BLANKENSHIP,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18705,18720,NaN,0,MILLSTONE,NaN,2.0,NaN,"[1] GE-3,[2] CE,[3] W-4-LP",JOHN DIAMOND,JOHN MacKINNON,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18706,18721,NaN,0,QUAD CITIES,1.0,2.0,NaN,"[1] GE-3,[2] GE-3",MORINE,JOHN MacKINNON,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18707,18722,NaN,0,SOUTH TEXAS,1.0,NaN,NaN,"[1] W-4-LP,[2] W-4-LP",NIEL,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18708,18723,NaN,0,SUSQUEHANNA,1.0,NaN,NaN,"[1] GE-4,[2] GE-4",STEFFENAUER,BILL RECKLEY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18709,18724,NaN,0,HUMBOLDT BAY,3.0,NaN,NaN,[3] GE-1,RIGNEY,RUDY KARSCH,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18710,18725,NaN,0,LASALLE,1.0,NaN,NaN,"[1] GE-5,[2] GE-5",TERMINI,RUDY KARSCH,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18711,18726,NaN,0,SAINT LUCIE,1.0,2.0,NaN,"[1] CE,[2] CE",M WOLAVER,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18712,18727,NaN,0,HATCH,1.0,NaN,NaN,"[1] GE-4,[2] GE-4",J ANDERSON,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18713,18728,NaN,0,ROBINSON,2.0,NaN,NaN,[2] W-3-LP,DOUG WINTERS,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18714,18729,NaN,0,TROJAN,1.0,NaN,NaN,[1] W-4-LP,J HEITZMAN,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18715,18730,NaN,0,POINT BEACH,1.0,NaN,NaN,"[1] W-2-LP,[2] W-2-LP","D. STEVENS, T. KOEHLER",RUDY KARSCH,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18716,18731,NaN,0,MILLSTONE,1.0,NaN,NaN,"[1] GE-3,[2] CE,[3] W-4-LP",BOWER,JOHN MacKINNON,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18717,18732,NaN,0,NORTH ANNA,1.0,2.0,NaN,"[1] W-3-LP,[2] W-3-LP",D DEVOR,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18718,18733,NaN,0,NINE MILE POINT,1.0,2.0,NaN,"[1] GE-2,[2] GE-5",F LUKACZYK,WILLIAM MATTINGLY,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN
18719,18734,NaN,0,PEACH BOTTOM,2.0,NaN,NaN,"[2] GE-4,[3] GE-4",BRYAN MERRYMAN,BOB SPENCE,...,0,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN

In [4]:
ens.dtypes

EventNotificationNumber             int64
RevisionNumber                    float64
RetractIndicator                    int64
SiteName                           object
UnitInd1                          float64
                                ...
ImportedDate               datetime64[ns]
OfInterest                           bool
Interest                           object
DocketNumber2                      object
DocketNumber3                     float64
Length: 86, dtype: object

In [5]:
ens.shape

(54772, 86)

In [6]:
#I only want the items of document type "POW" for this analysis as those are the power reactors
ens_pow = ens.loc[ens['DocumentTypeCode'] == 'POW']

In [9]:
ens_pow['SiteName'].unique()

array(['FT CALHOUN', 'PALISADES', 'YANKEE ROWE', 'NORTH ANNA',
       'MILLSTONE', 'QUAD CITIES', 'SOUTH TEXAS', 'SUSQUEHANNA',
       'HUMBOLDT BAY', 'LASALLE', 'SAINT LUCIE', 'HATCH', 'ROBINSON',
       'TROJAN', 'POINT BEACH', 'NINE MILE POINT', 'PEACH BOTTOM',
       'FERMI', 'PERRY', 'PALO VERDE', 'SEABROOK', 'INDIAN POINT',
       'BEAVER VALLEY', 'BROWNS FERRY', 'VOGTLE', 'PRAIRIE ISLAND',
       'CALVERT CLIFFS', 'MAINE YANKEE', 'BRAIDWOOD', 'CATAWBA', 'SALEM',
       'WATERFORD', 'TURKEY POINT', 'HADDAM NECK', 'COOK', 'BRUNSWICK',
       'ZION', 'LIMERICK', 'VERMONT YANKEE', 'HARRIS', 'FARLEY',
       'MCGUIRE', 'SUMMER', 'CLINTON', 'SEQUOYAH', 'COMANCHE PEAK',
       'ARKANSAS NUCLEAR', 'WASHINGTON NUCLEAR', 'CRYSTAL RIVER',
       'HOPE CREEK', 'GINNA', 'FITZPATRICK', 'MONTICELLO', 'DRESDEN',
       'SAN ONOFRE', 'DIABLO CANYON', 'RIVER BEND', 'COOPER',
       'OYSTER CREEK', 'THREE MILE ISLAND', 'DUANE ARNOLD', 'SHOREHAM',
       'BIG ROCK POINT', 'GRAND GULF', 'BYRON', 'OCONEE', 'KEWAUNEE',
       'DAVIS BESSE', 'PILGRIM', 'SURRY', 'CALLAWAY', 'WOLF CREEK',
       'RANCHO SECO', 'FT SAINT VRAIN', 'WATTS BAR', 'LACROSSE',
       'BELLEFONTE', 'WNP-2', 'WASHINGTON NUCLEAR (WNP-2)',
       'COLUMBIA GENERATING STATION', 'FORT CALHOUN',
       'SUMMER CONSTRUCTION', 'Palo Verde', 'Catawba', 'Sequoyah',
       'Browns Ferry', 'Byron', 'South Texas', 'Salem', 'Watts Bar',
       'Waterford', 'Grand Gulf', 'Fermi', 'Surry', 'Cook', 'Seabrook',
       'Brunswick', 'Mcguire', 'Summer', 'Beaver Valley', 'Turkey Point',
       'Millstone', 'Robinson', 'Oconee', 'Harris', 'Vogtle',
       'Diablo Canyon', 'Davis Besse', 'Prairie Island', 'Callaway',
       'Saint Lucie', 'Peach Bottom', 'Duane Arnold', 'Perry',
       'River Bend', 'Dresden', 'Palisades', 'Nine Mile Point', 'Pilgrim',
       'Fort Calhoun', 'FitzPatrick', 'North Anna', 'Quad Cities',
       'Comanche Peak', 'Point Beach', 'Monticello', 'Arkansas Nuclear'],
      dtype=object)

In [10]:
ens_pow['SiteName'] = ens_pow['SiteName'].str.upper()

C:\Users\CEN1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
ens_pow["SiteName"] = ens_pow["SiteName"].map({
        'FT CALHOUN': 'FORT CALHOUN',
        'ARKANSAS NUCLEAR': 'ARKANSAS NUCLEAR ONE',
        'COLUMBIA GENERATING STATION': 'COLUMBIA',
        }).fillna(ens_pow["SiteName"])

C:\Users\CEN1\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [12]:
ens_pow = ens_pow[(ens_pow.SiteName != "LACROSSE") & (ens_pow.SiteName != "RANCHO SECO") & (ens_pow.SiteName !="ZION") & (ens_pow.SiteName != "BELLEFONTE") & (ens_pow.SiteName != "HUMBOLDT BAY") & 
                      (ens_pow.SiteName != "HADDAM NECK") & (ens_pow.SiteName != "MAINE YANKEE") & 
                              (ens_pow.SiteName != "BIG ROCK POINT") & (ens_pow.SiteName != "TROJAN") & 
                              (ens_pow.SiteName != "FT SAINT VRAIN") & (ens_pow.SiteName != "WNP-2") & 
                              (ens_pow.SiteName != "WASHINGTON NUCLEAR") & (ens_pow.SiteName != "WASHINGTON NUCLEAR (WNP-2)") & 
                              (ens_pow.SiteName != "SHOREHAM") & 
                              (ens_pow.SiteName != "YANKEE ROWE") &
                              (ens_pow.SiteName != "SUMMER CONTRUCTION")]

In [13]:
ens_pow['UnitName'] = (ens_pow['SiteName'] + ' ' + ens_pow['UnitInd1'].astype(str) + ' ' + ens_pow['UnitInd2'].astype(str) + ' ' + ens_pow['UnitInd3'].astype(str))
#ens['UnitName'] = pd.Series(ens['SiteName'],ens['UnitInd1'].astype(str),ens['UnitInd2'].astype(str),ens['UnitInd3'].astype(str)).cat(sep=' ')

In [14]:
ens_pow.head()

,EventNotificationNumber,RevisionNumber,RetractIndicator,SiteName,UnitInd1,UnitInd2,UnitInd3,RxType,NrcNotifiedBy,OperationsOfficer,...,ReleaseDate,Note1,Note2,Note3,ImportedDate,OfInterest,Interest,DocketNumber2,DocketNumber3,UnitName
EventNotificationId,,,,,,,,,,,,,,,,,,,,,
18701,18716,NaN,0,FORT CALHOUN,1.0,NaN,NaN,[1] CE,BONSALL,BILL RECKLEY,...,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,FORT CALHOUN 1.0 nan nan
18702,18717,NaN,0,PALISADES,1.0,NaN,NaN,[1] CE,KUBACKI,BILL RECKLEY,...,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,PALISADES 1.0 nan nan
18704,18719,NaN,-1,NORTH ANNA,1.0,2.0,NaN,"[1] W-3-LP,[2] W-3-LP",BLANKENSHIP,BILL RECKLEY,...,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,NORTH ANNA 1.0 2.0 nan
18705,18720,NaN,0,MILLSTONE,NaN,2.0,NaN,"[1] GE-3,[2] CE,[3] W-4-LP",JOHN DIAMOND,JOHN MacKINNON,...,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,MILLSTONE nan 2.0 nan
18706,18721,NaN,0,QUAD CITIES,1.0,2.0,NaN,"[1] GE-3,[2] GE-3",MORINE,JOHN MacKINNON,...,NaT,NaN,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,QUAD CITIES 1.0 2.0 nan

In [15]:
ens_pow['RealName'] = ens_pow['UnitName'].str.replace('nan', '')

In [16]:
ens_pow['NameAgain'] = ens_pow['RealName'].str.replace('.0', '')

In [17]:
ens_pow.head()

,EventNotificationNumber,RevisionNumber,RetractIndicator,SiteName,UnitInd1,UnitInd2,UnitInd3,RxType,NrcNotifiedBy,OperationsOfficer,...,Note2,Note3,ImportedDate,OfInterest,Interest,DocketNumber2,DocketNumber3,UnitName,RealName,NameAgain
EventNotificationId,,,,,,,,,,,,,,,,,,,,,
18701,18716,NaN,0,FORT CALHOUN,1.0,NaN,NaN,[1] CE,BONSALL,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,FORT CALHOUN 1.0 nan nan,FORT CALHOUN 1.0,FORT CALHOUN 1
18702,18717,NaN,0,PALISADES,1.0,NaN,NaN,[1] CE,KUBACKI,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,PALISADES 1.0 nan nan,PALISADES 1.0,PALISADES 1
18704,18719,NaN,-1,NORTH ANNA,1.0,2.0,NaN,"[1] W-3-LP,[2] W-3-LP",BLANKENSHIP,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,NORTH ANNA 1.0 2.0 nan,NORTH ANNA 1.0 2.0,NORTH ANNA 1 2
18705,18720,NaN,0,MILLSTONE,NaN,2.0,NaN,"[1] GE-3,[2] CE,[3] W-4-LP",JOHN DIAMOND,JOHN MacKINNON,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,MILLSTONE nan 2.0 nan,MILLSTONE 2.0,MILLSTONE 2
18706,18721,NaN,0,QUAD CITIES,1.0,2.0,NaN,"[1] GE-3,[2] GE-3",MORINE,JOHN MacKINNON,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,QUAD CITIES 1.0 2.0 nan,QUAD CITIES 1.0 2.0,QUAD CITIES 1 2

In [18]:
ens_pow['NameAgain'].unique()

array(['FORT CALHOUN 1  ', 'PALISADES 1  ', 'NORTH ANNA 1 2 ',
       'MILLSTONE  2 ', 'QUAD CITIES 1 2 ', 'SOUTH TEXAS 1  ',
       'SUSQUEHANNA 1  ', 'LASALLE 1  ', 'SAINT LUCIE 1 2 ', 'HATCH 1  ',
       'ROBINSON 2  ', 'POINT BEACH 1  ', 'MILLSTONE 1  ',
       'NINE MILE POINT 1 2 ', 'PEACH BOTTOM 2  ', 'FERMI 2  ',
       'MILLSTONE   3', 'PERRY 1  ', 'PEACH BOTTOM  3 ', 'PALO VERDE 1  ',
       'SEABROOK 1  ', 'PEACH BOTTOM 2 3 ', 'SUSQUEHANNA  2 ',
       'INDIAN POINT 2  ', 'NINE MILE POINT  2 ', 'BEAVER VALLEY  2 ',
       'LASALLE  2 ', 'PALO VERDE  2 ', 'BROWNS FERRY 1  ', 'VOGTLE 1 2 ',
       'PRAIRIE ISLAND 1  ', 'CALVERT CLIFFS 1 2 ', 'NINE MILE POINT 1  ',
       'QUAD CITIES 1  ', 'BRAIDWOOD 1  ', 'POINT BEACH 1 2 ',
       'CATAWBA  2 ', 'SALEM 1  ', 'WATERFORD 3  ', 'TURKEY POINT  4 ',
       'COOK 1 2 ', 'BRUNSWICK 1 2 ', 'LIMERICK 1  ', 'HATCH  2 ',
       'INDIAN POINT  3 ', 'VERMONT YANKEE 1  ', 'SALEM  2 ',
       'HARRIS 1  ', 'BEAVER VALLEY 1 2 ', 'FARLEY 1 2 ', 'MCGUIRE  2 ',
       'SUMMER 1  ', 'CLINTON 1  ', 'BRUNSWICK  2 ', 'SEQUOYAH  2 ',
       'COMANCHE PEAK 1  ', 'ARKANSAS NUCLEAR ONE 1 2 ', 'SEQUOYAH 1 2 ',
       'CALVERT CLIFFS 1  ', 'PRAIRIE ISLAND  2 ', 'NORTH ANNA 1  ',
       'CRYSTAL RIVER 3  ', 'BROWNS FERRY 1 2 3', 'HOPE CREEK 1  ',
       'GINNA 1  ', 'SOUTH TEXAS  2 ', 'QUAD CITIES  2 ',
       'SUSQUEHANNA 1 2 ', 'FITZPATRICK 1  ', 'POINT BEACH  2 ',
       'CALVERT CLIFFS  2 ', 'BEAVER VALLEY 1  ', 'MONTICELLO 1  ',
       'DRESDEN  2 ', 'SAN ONOFRE  2 ', 'PALO VERDE   3', 'BRUNSWICK 1  ',
       'PRAIRIE ISLAND 1 2 ', 'VOGTLE  2 ', 'DRESDEN  2 3',
       'DIABLO CANYON 1 2 ', 'SAN ONOFRE 1  ', 'RIVER BEND 1  ',
       'COOPER 1  ', 'TURKEY POINT 3  ', 'OYSTER CREEK 1  ', 'HATCH 1 2 ',
       'THREE MILE ISLAND 1  ', 'DUANE ARNOLD 1  ', 'GRAND GULF 1  ',
       'BYRON  2 ', 'SOUTH TEXAS 1 2 ', 'OCONEE 1 2 3', 'MCGUIRE 1 2 ',
       'OCONEE   3', 'KEWAUNEE 1  ', 'DRESDEN   3', 'DAVIS BESSE 1  ',
       'PILGRIM 1  ', 'SURRY 1  ', 'LIMERICK  2 ', 'COMANCHE PEAK 1 2 ',
       'VOGTLE 1  ', 'CALLAWAY 1  ', 'WOLF CREEK 1  ', 'SURRY 1 2 ',
       'DIABLO CANYON  2 ', 'MCGUIRE 1  ', 'OCONEE 1  ', 'LIMERICK 1 2 ',
       'ARKANSAS NUCLEAR ONE  2 ', 'CATAWBA 1  ', 'COOK  2 ',
       'BYRON 1 2 ', 'ARKANSAS NUCLEAR ONE 1  ', 'BROWNS FERRY  2 ',
       'TURKEY POINT 3 4 ', 'SAINT LUCIE 1  ', 'BYRON 1  ',
       'LASALLE 1 2 ', 'SAN ONOFRE  2 3', 'BRAIDWOOD  2 ', 'SEQUOYAH 1  ',
       'DIABLO CANYON 1  ', 'FARLEY 1  ', 'BRAIDWOOD 1 2 ', 'SALEM 1 2 ',
       'THREE MILE ISLAND  2 ', 'FARLEY  2 ', 'SAN ONOFRE 1 2 3',
       'SURRY  2 ', 'SAINT LUCIE  2 ', 'BROWNS FERRY   3',
       'PALO VERDE 1 2 3', 'MILLSTONE 1 2 3', 'NORTH ANNA  2 ',
       'CATAWBA 1 2 ', 'SAN ONOFRE   3', 'WATTS BAR 1 2 ', 'COOK 1  ',
       'BROWNS FERRY 1 2 ', 'INDIAN POINT 2 3 ', 'OCONEE  2 ',
       'WATTS BAR 1  ', 'OCONEE  2 3', 'DRESDEN 1 2 3', 'OCONEE 1 2 ',
       'COMANCHE PEAK  2 ', 'PALO VERDE  2 3', 'THREE MILE ISLAND 1 2 ',
       'SALEM   ', 'BROWNS FERRY 1  3', 'OCONEE 1  3', 'PALO VERDE 1  3',
       'PALO VERDE 1 2 ', 'BROWNS FERRY  2 3', 'DRESDEN 1  ',
       'MILLSTONE 1 2 ', 'MCGUIRE   ', 'BYRON   ', 'CATAWBA   ',
       'DRESDEN 1 2 ', 'LASALLE   ', 'QUAD CITIES   ', 'MILLSTONE   ',
       'SAN ONOFRE 1  3', 'VOGTLE   ', 'SAN ONOFRE 1 2 ', 'COLUMBIA 2  ',
       'MILLSTONE  2 3', 'WATTS BAR  2 ', 'VOGTLE 3 4 ', 'NORTH ANNA 3  ',
       'SUMMER  2 3', 'SUMMER CONSTRUCTION 2 3 ', 'DRESDEN 2 3 ',
       'DRESDEN 2  ', 'VOGTLE  4 '], dtype=object)

In [19]:
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.strip()

In [20]:
ens_pow.head()

,EventNotificationNumber,RevisionNumber,RetractIndicator,SiteName,UnitInd1,UnitInd2,UnitInd3,RxType,NrcNotifiedBy,OperationsOfficer,...,Note2,Note3,ImportedDate,OfInterest,Interest,DocketNumber2,DocketNumber3,UnitName,RealName,NameAgain
EventNotificationId,,,,,,,,,,,,,,,,,,,,,
18701,18716,NaN,0,FORT CALHOUN,1.0,NaN,NaN,[1] CE,BONSALL,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,FORT CALHOUN 1.0 nan nan,FORT CALHOUN 1.0,FORT CALHOUN 1
18702,18717,NaN,0,PALISADES,1.0,NaN,NaN,[1] CE,KUBACKI,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,PALISADES 1.0 nan nan,PALISADES 1.0,PALISADES 1
18704,18719,NaN,-1,NORTH ANNA,1.0,2.0,NaN,"[1] W-3-LP,[2] W-3-LP",BLANKENSHIP,BILL RECKLEY,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,NORTH ANNA 1.0 2.0 nan,NORTH ANNA 1.0 2.0,NORTH ANNA 1 2
18705,18720,NaN,0,MILLSTONE,NaN,2.0,NaN,"[1] GE-3,[2] CE,[3] W-4-LP",JOHN DIAMOND,JOHN MacKINNON,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,MILLSTONE nan 2.0 nan,MILLSTONE 2.0,MILLSTONE 2
18706,18721,NaN,0,QUAD CITIES,1.0,2.0,NaN,"[1] GE-3,[2] GE-3",MORINE,JOHN MacKINNON,...,NaN,NaN,2003-04-10,False,NaN,NaN,NaN,QUAD CITIES 1.0 2.0 nan,QUAD CITIES 1.0 2.0,QUAD CITIES 1 2

In [21]:
ens_pow['NameAgain'].unique()

array(['FORT CALHOUN 1', 'PALISADES 1', 'NORTH ANNA 1 2', 'MILLSTONE  2',
       'QUAD CITIES 1 2', 'SOUTH TEXAS 1', 'SUSQUEHANNA 1', 'LASALLE 1',
       'SAINT LUCIE 1 2', 'HATCH 1', 'ROBINSON 2', 'POINT BEACH 1',
       'MILLSTONE 1', 'NINE MILE POINT 1 2', 'PEACH BOTTOM 2', 'FERMI 2',
       'MILLSTONE   3', 'PERRY 1', 'PEACH BOTTOM  3', 'PALO VERDE 1',
       'SEABROOK 1', 'PEACH BOTTOM 2 3', 'SUSQUEHANNA  2',
       'INDIAN POINT 2', 'NINE MILE POINT  2', 'BEAVER VALLEY  2',
       'LASALLE  2', 'PALO VERDE  2', 'BROWNS FERRY 1', 'VOGTLE 1 2',
       'PRAIRIE ISLAND 1', 'CALVERT CLIFFS 1 2', 'NINE MILE POINT 1',
       'QUAD CITIES 1', 'BRAIDWOOD 1', 'POINT BEACH 1 2', 'CATAWBA  2',
       'SALEM 1', 'WATERFORD 3', 'TURKEY POINT  4', 'COOK 1 2',
       'BRUNSWICK 1 2', 'LIMERICK 1', 'HATCH  2', 'INDIAN POINT  3',
       'VERMONT YANKEE 1', 'SALEM  2', 'HARRIS 1', 'BEAVER VALLEY 1 2',
       'FARLEY 1 2', 'MCGUIRE  2', 'SUMMER 1', 'CLINTON 1',
       'BRUNSWICK  2', 'SEQUOYAH  2', 'COMANCHE PEAK 1',
       'ARKANSAS NUCLEAR ONE 1 2', 'SEQUOYAH 1 2', 'CALVERT CLIFFS 1',
       'PRAIRIE ISLAND  2', 'NORTH ANNA 1', 'CRYSTAL RIVER 3',
       'BROWNS FERRY 1 2 3', 'HOPE CREEK 1', 'GINNA 1', 'SOUTH TEXAS  2',
       'QUAD CITIES  2', 'SUSQUEHANNA 1 2', 'FITZPATRICK 1',
       'POINT BEACH  2', 'CALVERT CLIFFS  2', 'BEAVER VALLEY 1',
       'MONTICELLO 1', 'DRESDEN  2', 'SAN ONOFRE  2', 'PALO VERDE   3',
       'BRUNSWICK 1', 'PRAIRIE ISLAND 1 2', 'VOGTLE  2', 'DRESDEN  2 3',
       'DIABLO CANYON 1 2', 'SAN ONOFRE 1', 'RIVER BEND 1', 'COOPER 1',
       'TURKEY POINT 3', 'OYSTER CREEK 1', 'HATCH 1 2',
       'THREE MILE ISLAND 1', 'DUANE ARNOLD 1', 'GRAND GULF 1',
       'BYRON  2', 'SOUTH TEXAS 1 2', 'OCONEE 1 2 3', 'MCGUIRE 1 2',
       'OCONEE   3', 'KEWAUNEE 1', 'DRESDEN   3', 'DAVIS BESSE 1',
       'PILGRIM 1', 'SURRY 1', 'LIMERICK  2', 'COMANCHE PEAK 1 2',
       'VOGTLE 1', 'CALLAWAY 1', 'WOLF CREEK 1', 'SURRY 1 2',
       'DIABLO CANYON  2', 'MCGUIRE 1', 'OCONEE 1', 'LIMERICK 1 2',
       'ARKANSAS NUCLEAR ONE  2', 'CATAWBA 1', 'COOK  2', 'BYRON 1 2',
       'ARKANSAS NUCLEAR ONE 1', 'BROWNS FERRY  2', 'TURKEY POINT 3 4',
       'SAINT LUCIE 1', 'BYRON 1', 'LASALLE 1 2', 'SAN ONOFRE  2 3',
       'BRAIDWOOD  2', 'SEQUOYAH 1', 'DIABLO CANYON 1', 'FARLEY 1',
       'BRAIDWOOD 1 2', 'SALEM 1 2', 'THREE MILE ISLAND  2', 'FARLEY  2',
       'SAN ONOFRE 1 2 3', 'SURRY  2', 'SAINT LUCIE  2',
       'BROWNS FERRY   3', 'PALO VERDE 1 2 3', 'MILLSTONE 1 2 3',
       'NORTH ANNA  2', 'CATAWBA 1 2', 'SAN ONOFRE   3', 'WATTS BAR 1 2',
       'COOK 1', 'BROWNS FERRY 1 2', 'INDIAN POINT 2 3', 'OCONEE  2',
       'WATTS BAR 1', 'OCONEE  2 3', 'DRESDEN 1 2 3', 'OCONEE 1 2',
       'COMANCHE PEAK  2', 'PALO VERDE  2 3', 'THREE MILE ISLAND 1 2',
       'SALEM', 'BROWNS FERRY 1  3', 'OCONEE 1  3', 'PALO VERDE 1  3',
       'PALO VERDE 1 2', 'BROWNS FERRY  2 3', 'DRESDEN 1',
       'MILLSTONE 1 2', 'MCGUIRE', 'BYRON', 'CATAWBA', 'DRESDEN 1 2',
       'LASALLE', 'QUAD CITIES', 'MILLSTONE', 'SAN ONOFRE 1  3', 'VOGTLE',
       'SAN ONOFRE 1 2', 'COLUMBIA 2', 'MILLSTONE  2 3', 'WATTS BAR  2',
       'VOGTLE 3 4', 'NORTH ANNA 3', 'SUMMER  2 3',
       'SUMMER CONSTRUCTION 2 3', 'DRESDEN 2 3', 'DRESDEN 2', 'VOGTLE  4'],
      dtype=object)

In [22]:
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('  ', ' ')

In [23]:
ens_pow['NameAgain'].unique()

array(['FORT CALHOUN 1', 'PALISADES 1', 'NORTH ANNA 1 2', 'MILLSTONE 2',
       'QUAD CITIES 1 2', 'SOUTH TEXAS 1', 'SUSQUEHANNA 1', 'LASALLE 1',
       'SAINT LUCIE 1 2', 'HATCH 1', 'ROBINSON 2', 'POINT BEACH 1',
       'MILLSTONE 1', 'NINE MILE POINT 1 2', 'PEACH BOTTOM 2', 'FERMI 2',
       'MILLSTONE  3', 'PERRY 1', 'PEACH BOTTOM 3', 'PALO VERDE 1',
       'SEABROOK 1', 'PEACH BOTTOM 2 3', 'SUSQUEHANNA 2',
       'INDIAN POINT 2', 'NINE MILE POINT 2', 'BEAVER VALLEY 2',
       'LASALLE 2', 'PALO VERDE 2', 'BROWNS FERRY 1', 'VOGTLE 1 2',
       'PRAIRIE ISLAND 1', 'CALVERT CLIFFS 1 2', 'NINE MILE POINT 1',
       'QUAD CITIES 1', 'BRAIDWOOD 1', 'POINT BEACH 1 2', 'CATAWBA 2',
       'SALEM 1', 'WATERFORD 3', 'TURKEY POINT 4', 'COOK 1 2',
       'BRUNSWICK 1 2', 'LIMERICK 1', 'HATCH 2', 'INDIAN POINT 3',
       'VERMONT YANKEE 1', 'SALEM 2', 'HARRIS 1', 'BEAVER VALLEY 1 2',
       'FARLEY 1 2', 'MCGUIRE 2', 'SUMMER 1', 'CLINTON 1', 'BRUNSWICK 2',
       'SEQUOYAH 2', 'COMANCHE PEAK 1', 'ARKANSAS NUCLEAR ONE 1 2',
       'SEQUOYAH 1 2', 'CALVERT CLIFFS 1', 'PRAIRIE ISLAND 2',
       'NORTH ANNA 1', 'CRYSTAL RIVER 3', 'BROWNS FERRY 1 2 3',
       'HOPE CREEK 1', 'GINNA 1', 'SOUTH TEXAS 2', 'QUAD CITIES 2',
       'SUSQUEHANNA 1 2', 'FITZPATRICK 1', 'POINT BEACH 2',
       'CALVERT CLIFFS 2', 'BEAVER VALLEY 1', 'MONTICELLO 1', 'DRESDEN 2',
       'SAN ONOFRE 2', 'PALO VERDE  3', 'BRUNSWICK 1',
       'PRAIRIE ISLAND 1 2', 'VOGTLE 2', 'DRESDEN 2 3',
       'DIABLO CANYON 1 2', 'SAN ONOFRE 1', 'RIVER BEND 1', 'COOPER 1',
       'TURKEY POINT 3', 'OYSTER CREEK 1', 'HATCH 1 2',
       'THREE MILE ISLAND 1', 'DUANE ARNOLD 1', 'GRAND GULF 1', 'BYRON 2',
       'SOUTH TEXAS 1 2', 'OCONEE 1 2 3', 'MCGUIRE 1 2', 'OCONEE  3',
       'KEWAUNEE 1', 'DRESDEN  3', 'DAVIS BESSE 1', 'PILGRIM 1',
       'SURRY 1', 'LIMERICK 2', 'COMANCHE PEAK 1 2', 'VOGTLE 1',
       'CALLAWAY 1', 'WOLF CREEK 1', 'SURRY 1 2', 'DIABLO CANYON 2',
       'MCGUIRE 1', 'OCONEE 1', 'LIMERICK 1 2', 'ARKANSAS NUCLEAR ONE 2',
       'CATAWBA 1', 'COOK 2', 'BYRON 1 2', 'ARKANSAS NUCLEAR ONE 1',
       'BROWNS FERRY 2', 'TURKEY POINT 3 4', 'SAINT LUCIE 1', 'BYRON 1',
       'LASALLE 1 2', 'SAN ONOFRE 2 3', 'BRAIDWOOD 2', 'SEQUOYAH 1',
       'DIABLO CANYON 1', 'FARLEY 1', 'BRAIDWOOD 1 2', 'SALEM 1 2',
       'THREE MILE ISLAND 2', 'FARLEY 2', 'SAN ONOFRE 1 2 3', 'SURRY 2',
       'SAINT LUCIE 2', 'BROWNS FERRY  3', 'PALO VERDE 1 2 3',
       'MILLSTONE 1 2 3', 'NORTH ANNA 2', 'CATAWBA 1 2', 'SAN ONOFRE  3',
       'WATTS BAR 1 2', 'COOK 1', 'BROWNS FERRY 1 2', 'INDIAN POINT 2 3',
       'OCONEE 2', 'WATTS BAR 1', 'OCONEE 2 3', 'DRESDEN 1 2 3',
       'OCONEE 1 2', 'COMANCHE PEAK 2', 'PALO VERDE 2 3',
       'THREE MILE ISLAND 1 2', 'SALEM', 'BROWNS FERRY 1 3', 'OCONEE 1 3',
       'PALO VERDE 1 3', 'PALO VERDE 1 2', 'BROWNS FERRY 2 3',
       'DRESDEN 1', 'MILLSTONE 1 2', 'MCGUIRE', 'BYRON', 'CATAWBA',
       'DRESDEN 1 2', 'LASALLE', 'QUAD CITIES', 'MILLSTONE',
       'SAN ONOFRE 1 3', 'VOGTLE', 'SAN ONOFRE 1 2', 'COLUMBIA 2',
       'MILLSTONE 2 3', 'WATTS BAR 2', 'VOGTLE 3 4', 'NORTH ANNA 3',
       'SUMMER 2 3', 'SUMMER CONSTRUCTION 2 3', 'VOGTLE 4'], dtype=object)

In [24]:
ens_pow['NameAgain'].sort_values(ascending=True).unique()

array(['ARKANSAS NUCLEAR ONE 1', 'ARKANSAS NUCLEAR ONE 1 2',
       'ARKANSAS NUCLEAR ONE 2', 'BEAVER VALLEY 1', 'BEAVER VALLEY 1 2',
       'BEAVER VALLEY 2', 'BRAIDWOOD 1', 'BRAIDWOOD 1 2', 'BRAIDWOOD 2',
       'BROWNS FERRY  3', 'BROWNS FERRY 1', 'BROWNS FERRY 1 2',
       'BROWNS FERRY 1 2 3', 'BROWNS FERRY 1 3', 'BROWNS FERRY 2',
       'BROWNS FERRY 2 3', 'BRUNSWICK 1', 'BRUNSWICK 1 2', 'BRUNSWICK 2',
       'BYRON', 'BYRON 1', 'BYRON 1 2', 'BYRON 2', 'CALLAWAY 1',
       'CALVERT CLIFFS 1', 'CALVERT CLIFFS 1 2', 'CALVERT CLIFFS 2',
       'CATAWBA', 'CATAWBA 1', 'CATAWBA 1 2', 'CATAWBA 2', 'CLINTON 1',
       'COLUMBIA 2', 'COMANCHE PEAK 1', 'COMANCHE PEAK 1 2',
       'COMANCHE PEAK 2', 'COOK 1', 'COOK 1 2', 'COOK 2', 'COOPER 1',
       'CRYSTAL RIVER 3', 'DAVIS BESSE 1', 'DIABLO CANYON 1',
       'DIABLO CANYON 1 2', 'DIABLO CANYON 2', 'DRESDEN  3', 'DRESDEN 1',
       'DRESDEN 1 2', 'DRESDEN 1 2 3', 'DRESDEN 2', 'DRESDEN 2 3',
       'DUANE ARNOLD 1', 'FARLEY 1', 'FARLEY 1 2', 'FARLEY 2', 'FERMI 2',
       'FITZPATRICK 1', 'FORT CALHOUN 1', 'GINNA 1', 'GRAND GULF 1',
       'HARRIS 1', 'HATCH 1', 'HATCH 1 2', 'HATCH 2', 'HOPE CREEK 1',
       'INDIAN POINT 2', 'INDIAN POINT 2 3', 'INDIAN POINT 3',
       'KEWAUNEE 1', 'LASALLE', 'LASALLE 1', 'LASALLE 1 2', 'LASALLE 2',
       'LIMERICK 1', 'LIMERICK 1 2', 'LIMERICK 2', 'MCGUIRE', 'MCGUIRE 1',
       'MCGUIRE 1 2', 'MCGUIRE 2', 'MILLSTONE', 'MILLSTONE  3',
       'MILLSTONE 1', 'MILLSTONE 1 2', 'MILLSTONE 1 2 3', 'MILLSTONE 2',
       'MILLSTONE 2 3', 'MONTICELLO 1', 'NINE MILE POINT 1',
       'NINE MILE POINT 1 2', 'NINE MILE POINT 2', 'NORTH ANNA 1',
       'NORTH ANNA 1 2', 'NORTH ANNA 2', 'NORTH ANNA 3', 'OCONEE  3',
       'OCONEE 1', 'OCONEE 1 2', 'OCONEE 1 2 3', 'OCONEE 1 3', 'OCONEE 2',
       'OCONEE 2 3', 'OYSTER CREEK 1', 'PALISADES 1', 'PALO VERDE  3',
       'PALO VERDE 1', 'PALO VERDE 1 2', 'PALO VERDE 1 2 3',
       'PALO VERDE 1 3', 'PALO VERDE 2', 'PALO VERDE 2 3',
       'PEACH BOTTOM 2', 'PEACH BOTTOM 2 3', 'PEACH BOTTOM 3', 'PERRY 1',
       'PILGRIM 1', 'POINT BEACH 1', 'POINT BEACH 1 2', 'POINT BEACH 2',
       'PRAIRIE ISLAND 1', 'PRAIRIE ISLAND 1 2', 'PRAIRIE ISLAND 2',
       'QUAD CITIES', 'QUAD CITIES 1', 'QUAD CITIES 1 2', 'QUAD CITIES 2',
       'RIVER BEND 1', 'ROBINSON 2', 'SAINT LUCIE 1', 'SAINT LUCIE 1 2',
       'SAINT LUCIE 2', 'SALEM', 'SALEM 1', 'SALEM 1 2', 'SALEM 2',
       'SAN ONOFRE  3', 'SAN ONOFRE 1', 'SAN ONOFRE 1 2',
       'SAN ONOFRE 1 2 3', 'SAN ONOFRE 1 3', 'SAN ONOFRE 2',
       'SAN ONOFRE 2 3', 'SEABROOK 1', 'SEQUOYAH 1', 'SEQUOYAH 1 2',
       'SEQUOYAH 2', 'SOUTH TEXAS 1', 'SOUTH TEXAS 1 2', 'SOUTH TEXAS 2',
       'SUMMER 1', 'SUMMER 2 3', 'SUMMER CONSTRUCTION 2 3', 'SURRY 1',
       'SURRY 1 2', 'SURRY 2', 'SUSQUEHANNA 1', 'SUSQUEHANNA 1 2',
       'SUSQUEHANNA 2', 'THREE MILE ISLAND 1', 'THREE MILE ISLAND 1 2',
       'THREE MILE ISLAND 2', 'TURKEY POINT 3', 'TURKEY POINT 3 4',
       'TURKEY POINT 4', 'VERMONT YANKEE 1', 'VOGTLE', 'VOGTLE 1',
       'VOGTLE 1 2', 'VOGTLE 2', 'VOGTLE 3 4', 'VOGTLE 4', 'WATERFORD 3',
       'WATTS BAR 1', 'WATTS BAR 1 2', 'WATTS BAR 2', 'WOLF CREEK 1'],
      dtype=object)

In [25]:
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('1 2', '1')
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('2 3', '2')
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('1 3', '1')
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('3 4', '3')
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('1 2 3', '1')
ens_pow['NameAgain'] = ens_pow['NameAgain'].str.replace('  3', ' 3')

In [26]:
ens_pow["NameAgain"] = ens_pow["NameAgain"].map({
        'BYRON': 'BYRON 1',
        'CATAWBA': 'CATAWBA 1',
        'DAVIS BESSE 1': 'DAVIS-BESSE',
        'LASALLE': 'LASALLE 1',
        'MCGUIRE': 'MCGUIRE 1',
        'MILLSTONE': 'MILLSTONE 1',
        'QUAD CITIES': 'QUAD CITIES 1',
        'SALEM': 'SALEM 1',
        'VOGTLE': 'VOGTLE 1'
        }).fillna(ens_pow["NameAgain"])

In [27]:
ens_pow['NameAgain'].sort_values(ascending=True).unique()

array(['ARKANSAS NUCLEAR ONE 1', 'ARKANSAS NUCLEAR ONE 2',
       'BEAVER VALLEY 1', 'BEAVER VALLEY 2', 'BRAIDWOOD 1', 'BRAIDWOOD 2',
       'BROWNS FERRY 1', 'BROWNS FERRY 2', 'BROWNS FERRY 3',
       'BRUNSWICK 1', 'BRUNSWICK 2', 'BYRON 1', 'BYRON 2', 'CALLAWAY 1',
       'CALVERT CLIFFS 1', 'CALVERT CLIFFS 2', 'CATAWBA 1', 'CATAWBA 2',
       'CLINTON 1', 'COLUMBIA 2', 'COMANCHE PEAK 1', 'COMANCHE PEAK 2',
       'COOK 1', 'COOK 2', 'COOPER 1', 'CRYSTAL RIVER 3', 'DAVIS-BESSE',
       'DIABLO CANYON 1', 'DIABLO CANYON 2', 'DRESDEN 1', 'DRESDEN 2',
       'DRESDEN 3', 'DUANE ARNOLD 1', 'FARLEY 1', 'FARLEY 2', 'FERMI 2',
       'FITZPATRICK 1', 'FORT CALHOUN 1', 'GINNA 1', 'GRAND GULF 1',
       'HARRIS 1', 'HATCH 1', 'HATCH 2', 'HOPE CREEK 1', 'INDIAN POINT 2',
       'INDIAN POINT 3', 'KEWAUNEE 1', 'LASALLE 1', 'LASALLE 2',
       'LIMERICK 1', 'LIMERICK 2', 'MCGUIRE 1', 'MCGUIRE 2',
       'MILLSTONE 1', 'MILLSTONE 2', 'MILLSTONE 3', 'MONTICELLO 1',
       'NINE MILE POINT 1', 'NINE MILE POINT 2', 'NORTH ANNA 1',
       'NORTH ANNA 2', 'NORTH ANNA 3', 'OCONEE 1', 'OCONEE 2', 'OCONEE 3',
       'OYSTER CREEK 1', 'PALISADES 1', 'PALO VERDE 1', 'PALO VERDE 2',
       'PALO VERDE 3', 'PEACH BOTTOM 2', 'PEACH BOTTOM 3', 'PERRY 1',
       'PILGRIM 1', 'POINT BEACH 1', 'POINT BEACH 2', 'PRAIRIE ISLAND 1',
       'PRAIRIE ISLAND 2', 'QUAD CITIES 1', 'QUAD CITIES 2',
       'RIVER BEND 1', 'ROBINSON 2', 'SAINT LUCIE 1', 'SAINT LUCIE 2',
       'SALEM 1', 'SALEM 2', 'SAN ONOFRE 1', 'SAN ONOFRE 2',
       'SAN ONOFRE 3', 'SEABROOK 1', 'SEQUOYAH 1', 'SEQUOYAH 2',
       'SOUTH TEXAS 1', 'SOUTH TEXAS 2', 'SUMMER 1', 'SUMMER 2',
       'SUMMER CONSTRUCTION 2', 'SURRY 1', 'SURRY 2', 'SUSQUEHANNA 1',
       'SUSQUEHANNA 2', 'THREE MILE ISLAND 1', 'THREE MILE ISLAND 2',
       'TURKEY POINT 3', 'TURKEY POINT 4', 'VERMONT YANKEE 1', 'VOGTLE 1',
       'VOGTLE 2', 'VOGTLE 3', 'VOGTLE 4', 'WATERFORD 3', 'WATTS BAR 1',
       'WATTS BAR 2', 'WOLF CREEK 1'], dtype=object)

In [28]:
ens_pow["NameAgain"] = ens_pow["NameAgain"].map({
        'ARKANSAS NUCLEAR ONE 1': 'ARKANSAS NUCLEAR 1',
        'ARKANSAS NUCLEAR ONE 2': 'ARKANSAS NUCLEAR 2',
        'CALLAWAY 1': 'CALLAWAY',
        'CLINTON 1': 'CLINTON',
        'COLUMBIA 2': 'COLUMBIA GENERATING STATION',
        'COOK 1': 'D.C. COOK 1',
        'COOK 2': 'D.C. COOK 2',
        'COOPER 1': 'COOPER',
        'DAVIS BESSE 1': 'DAVIS-BESSE',
        'DUANE ARNOLD 1': 'DUANE ARNOLD',
        'FITZPATRICK 1': 'FITZPATRICK',
        'FORT CALHOUN 1': 'FORT CALHOUN',
        'GINNA 1': 'GINNA',
        'LASALLE': 'LASALLE 1',
        'MCGUIRE': 'MCGUIRE 1',
        'MILLSTONE': 'MILLSTONE 1',
        'MONTICELLO 1': 'MONTICELLO',
        'OYSTER CREEK 1': 'OYSTER CREEK',
        'PALISADES 1': 'PALISADES',
        'QUAD CITIES': 'QUAD CITIES 1',
        'SALEM': 'SALEM 1',
        'SUMMER 1': 'SUMMER',
        'VERMONT YANKEE 1': 'VERMONT YANKEE',
        'VOGTLE': 'VOGTLE 1'
        }).fillna(ens_pow["NameAgain"])

In [29]:
ens_pow = ens_pow[(ens_pow.NameAgain != "DRESDEN 1") & (ens_pow.NameAgain != "MILLSTONE 1") & (ens_pow.NameAgain !="NORTH ANNA 3") & (ens_pow.NameAgain != "SAN ONOFRE 1") & (ens_pow.NameAgain != "SUMMER 2") & 
                      (ens_pow.NameAgain != "SUMMER CONSTRUCTION 2") & (ens_pow.NameAgain != "THREE MILE ISLAND 2") & 
                              (ens_pow.NameAgain != "VOGTLE 3") & (ens_pow.NameAgain != "VOGTLE 4")]

In [30]:
ens_pow['NameAgain'].sort_values(ascending=True).unique()

array(['ARKANSAS NUCLEAR 1', 'ARKANSAS NUCLEAR 2', 'BEAVER VALLEY 1',
       'BEAVER VALLEY 2', 'BRAIDWOOD 1', 'BRAIDWOOD 2', 'BROWNS FERRY 1',
       'BROWNS FERRY 2', 'BROWNS FERRY 3', 'BRUNSWICK 1', 'BRUNSWICK 2',
       'BYRON 1', 'BYRON 2', 'CALLAWAY', 'CALVERT CLIFFS 1',
       'CALVERT CLIFFS 2', 'CATAWBA 1', 'CATAWBA 2', 'CLINTON',
       'COLUMBIA GENERATING STATION', 'COMANCHE PEAK 1',
       'COMANCHE PEAK 2', 'COOPER', 'CRYSTAL RIVER 3', 'D.C. COOK 1',
       'D.C. COOK 2', 'DAVIS-BESSE', 'DIABLO CANYON 1', 'DIABLO CANYON 2',
       'DRESDEN 2', 'DRESDEN 3', 'DUANE ARNOLD', 'FARLEY 1', 'FARLEY 2',
       'FERMI 2', 'FITZPATRICK', 'FORT CALHOUN', 'GINNA', 'GRAND GULF 1',
       'HARRIS 1', 'HATCH 1', 'HATCH 2', 'HOPE CREEK 1', 'INDIAN POINT 2',
       'INDIAN POINT 3', 'KEWAUNEE 1', 'LASALLE 1', 'LASALLE 2',
       'LIMERICK 1', 'LIMERICK 2', 'MCGUIRE 1', 'MCGUIRE 2',
       'MILLSTONE 2', 'MILLSTONE 3', 'MONTICELLO', 'NINE MILE POINT 1',
       'NINE MILE POINT 2', 'NORTH ANNA 1', 'NORTH ANNA 2', 'OCONEE 1',
       'OCONEE 2', 'OCONEE 3', 'OYSTER CREEK', 'PALISADES',
       'PALO VERDE 1', 'PALO VERDE 2', 'PALO VERDE 3', 'PEACH BOTTOM 2',
       'PEACH BOTTOM 3', 'PERRY 1', 'PILGRIM 1', 'POINT BEACH 1',
       'POINT BEACH 2', 'PRAIRIE ISLAND 1', 'PRAIRIE ISLAND 2',
       'QUAD CITIES 1', 'QUAD CITIES 2', 'RIVER BEND 1', 'ROBINSON 2',
       'SAINT LUCIE 1', 'SAINT LUCIE 2', 'SALEM 1', 'SALEM 2',
       'SAN ONOFRE 2', 'SAN ONOFRE 3', 'SEABROOK 1', 'SEQUOYAH 1',
       'SEQUOYAH 2', 'SOUTH TEXAS 1', 'SOUTH TEXAS 2', 'SUMMER',
       'SURRY 1', 'SURRY 2', 'SUSQUEHANNA 1', 'SUSQUEHANNA 2',
       'THREE MILE ISLAND 1', 'TURKEY POINT 3', 'TURKEY POINT 4',
       'VERMONT YANKEE', 'VOGTLE 1', 'VOGTLE 2', 'WATERFORD 3',
       'WATTS BAR 1', 'WATTS BAR 2', 'WOLF CREEK 1'], dtype=object)

In [31]:
ens_pow.dtypes

EventNotificationNumber      int64
RevisionNumber             float64
RetractIndicator             int64
SiteName                    object
UnitInd1                   float64
                            ...
DocketNumber2               object
DocketNumber3              float64
UnitName                    object
RealName                    object
NameAgain                   object
Length: 89, dtype: object

In [32]:
ens_pow['NameAgain'].isnull().sum()

0

In [33]:
ens_pow.shape

(39081, 89)

In [34]:
ens_pow.columns

Index(['EventNotificationNumber', 'RevisionNumber', 'RetractIndicator',
       'SiteName', 'UnitInd1', 'UnitInd2', 'UnitInd3', 'RxType',
       'NrcNotifiedBy', 'OperationsOfficer', 'EventDate', 'NotificationDate',
       'DateUpdated', 'StaffName1', 'StaffName2', 'StaffName3', 'StaffName4',
       'StaffName5', 'StaffName6', 'StaffName7', 'StaffName8', 'StaffName9',
       'StaffName10', 'OrgAbbreviation1', 'OrgAbbreviation2',
       'OrgAbbreviation3', 'OrgAbbreviation4', 'OrgAbbreviation5',
       'OrgAbbreviation6', 'OrgAbbreviation7', 'OrgAbbreviation8',
       'OrgAbbreviation9', 'OrgAbbreviation10', 'Text', 'CurrPower1',
       'CurrPower2', 'CurrPower3', 'InitPower1', 'InitPower2', 'InitPower3',
       'CriticalIndicator1', 'CriticalIndicator2', 'CriticalIndicator3',
       'ScramType1', 'ScramType2', 'ScramType3', 'EventDescription',
       'CfrDescription1', 'CfrDescription2', 'CfrDescription3',
       'CfrDescription4', 'IMode1', 'IMode2', 'IMode3', 'FMode1', 'FMode2',
       'FMode3', 'EmergencyClass', 'DocketNumber', 'RegionNumber', 'StateCode',
       'TimeZone', 'AgreementStateInd', 'LicenseeName', 'LicenseNumber',
       'CityName', 'CountyName', 'ContainmentType1', 'ContainmentType2',
       'ContainmentType3', 'DocumentTypeCode', 'SubType', 'CfrCode1',
       'CfrCode2', 'CfrCode3', 'CfrCode4', 'Security', 'ReleaseDate', 'Note1',
       'Note2', 'Note3', 'ImportedDate', 'OfInterest', 'Interest',
       'DocketNumber2', 'DocketNumber3', 'UnitName', 'RealName', 'NameAgain'],
      dtype='object')

In [35]:
#choosing just the columns that I believe I will need for this analysis
ens_clean = ens_pow[['EventNotificationNumber', 'SiteName', 'EventDate', 'NotificationDate', 'Text', 'CurrPower1', 'CurrPower2', 'CurrPower3', 'InitPower1', 'InitPower2', 'InitPower3', 'ImportedDate', 'NameAgain']]

In [36]:
ens_clean.shape

(39081, 13)

In [37]:
ens_clean.dtypes

EventNotificationNumber             int64
SiteName                           object
EventDate                  datetime64[ns]
NotificationDate           datetime64[ns]
Text                               object
CurrPower1                        float64
CurrPower2                        float64
CurrPower3                        float64
InitPower1                        float64
InitPower2                        float64
InitPower3                        float64
ImportedDate               datetime64[ns]
NameAgain                          object
dtype: object

In [38]:
ens_clean.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain
EventNotificationId,,,,,,,,,,,,,
18701,18716,FORT CALHOUN,1990-06-15 18:24:00,1990-06-15 18:24:00,LICENSEE PLANS TO DISABLE THE CONTROL ROOM ENS...,94.0,0.0,0.0,94.0,0.0,0.0,2003-04-10,FORT CALHOUN
18702,18717,PALISADES,1990-06-15 20:10:00,1990-06-15 22:49:00,THE UNIT EXPERIENCED A REACTOR PROTECTION SYST...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,PALISADES
18704,18719,NORTH ANNA,1990-06-16 14:53:00,1990-06-16 18:47:00,LICENSEE DISCOVERED THAT THE SEISMIC SUPPORTS ...,100.0,100.0,0.0,100.0,100.0,0.0,2003-04-10,NORTH ANNA 1
18705,18720,MILLSTONE,1990-06-17 01:18:00,1990-06-17 02:25:00,"CHANGING INDICATOR LIGHT ON ""B"" EDG LOAD SEQUE...",0.0,89.0,0.0,0.0,89.0,0.0,2003-04-10,MILLSTONE 2
18706,18721,QUAD CITIES,1990-06-17 03:13:00,1990-06-17 04:48:00,SAFEGUARDS DEGRADATION DUE TO LOSS OF SECURITY...,98.0,99.0,0.0,98.0,99.0,0.0,2003-04-10,QUAD CITIES 1

In [39]:
ens_clean.loc[48072]

EventNotificationNumber                                                49195
SiteName                                                             CATAWBA
EventDate                                                                NaT
NotificationDate                                         2013-07-16 14:20:00
Text                       60 DAY REPORT - INVALID ACTUATION OF SPECIFIED...
CurrPower1                                                               100
CurrPower2                                                               100
CurrPower3                                                                 0
InitPower1                                                               100
InitPower2                                                               100
InitPower3                                                                 0
ImportedDate                                      2018-06-13 12:25:01.117000
NameAgain                                                          CATAWBA 1
Name: 48072, dtype: object

In [40]:
ens_clean.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain
EventNotificationId,,,,,,,,,,,,,
18701,18716,FORT CALHOUN,1990-06-15 18:24:00,1990-06-15 18:24:00,LICENSEE PLANS TO DISABLE THE CONTROL ROOM ENS...,94.0,0.0,0.0,94.0,0.0,0.0,2003-04-10,FORT CALHOUN
18702,18717,PALISADES,1990-06-15 20:10:00,1990-06-15 22:49:00,THE UNIT EXPERIENCED A REACTOR PROTECTION SYST...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,PALISADES
18704,18719,NORTH ANNA,1990-06-16 14:53:00,1990-06-16 18:47:00,LICENSEE DISCOVERED THAT THE SEISMIC SUPPORTS ...,100.0,100.0,0.0,100.0,100.0,0.0,2003-04-10,NORTH ANNA 1
18705,18720,MILLSTONE,1990-06-17 01:18:00,1990-06-17 02:25:00,"CHANGING INDICATOR LIGHT ON ""B"" EDG LOAD SEQUE...",0.0,89.0,0.0,0.0,89.0,0.0,2003-04-10,MILLSTONE 2
18706,18721,QUAD CITIES,1990-06-17 03:13:00,1990-06-17 04:48:00,SAFEGUARDS DEGRADATION DUE TO LOSS OF SECURITY...,98.0,99.0,0.0,98.0,99.0,0.0,2003-04-10,QUAD CITIES 1

In [41]:
ens_clean["EventDate"].unique()

array(['1990-06-15T18:24:00.000000000', '1990-06-15T20:10:00.000000000',
       '1990-06-16T14:53:00.000000000', ...,
       '1990-06-14T15:55:00.000000000', '1990-06-15T09:50:00.000000000',
       '1990-06-15T12:03:00.000000000'], dtype='datetime64[ns]')

In [42]:
#checking out a specific row as a spot check
ens_clean.loc[48064]

EventNotificationNumber                                                49187
SiteName                                                             PILGRIM
EventDate                                                                NaT
NotificationDate                                         2013-07-11 19:49:00
Text                       FITNESS-FOR-DUTY REPORT INVOLVING A NON-LICENS...
CurrPower1                                                               100
CurrPower2                                                                 0
CurrPower3                                                                 0
InitPower1                                                               100
InitPower2                                                                 0
InitPower3                                                                 0
ImportedDate                                      2018-06-13 12:25:01.087000
NameAgain                                                          PILGRIM 1
Name: 48064, dtype: object

In [44]:
#creating a new column of Year to make the EventDate column just the date
ens_clean['Year'] = ens_clean['EventDate'].astype(str).str[:10]

C:\Users\CEN1\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [78]:
#ens_clean['IntEventDate'] = ens_clean['Year'].str.replace("-","")

C:\Users\CEN1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [45]:
ens_clean.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
18701,18716,FORT CALHOUN,1990-06-15 18:24:00,1990-06-15 18:24:00,LICENSEE PLANS TO DISABLE THE CONTROL ROOM ENS...,94.0,0.0,0.0,94.0,0.0,0.0,2003-04-10,FORT CALHOUN,1990-06-15
18702,18717,PALISADES,1990-06-15 20:10:00,1990-06-15 22:49:00,THE UNIT EXPERIENCED A REACTOR PROTECTION SYST...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,PALISADES,1990-06-15
18704,18719,NORTH ANNA,1990-06-16 14:53:00,1990-06-16 18:47:00,LICENSEE DISCOVERED THAT THE SEISMIC SUPPORTS ...,100.0,100.0,0.0,100.0,100.0,0.0,2003-04-10,NORTH ANNA 1,1990-06-16
18705,18720,MILLSTONE,1990-06-17 01:18:00,1990-06-17 02:25:00,"CHANGING INDICATOR LIGHT ON ""B"" EDG LOAD SEQUE...",0.0,89.0,0.0,0.0,89.0,0.0,2003-04-10,MILLSTONE 2,1990-06-17
18706,18721,QUAD CITIES,1990-06-17 03:13:00,1990-06-17 04:48:00,SAFEGUARDS DEGRADATION DUE TO LOSS OF SECURITY...,98.0,99.0,0.0,98.0,99.0,0.0,2003-04-10,QUAD CITIES 1,1990-06-17

In [46]:
ens_clean['Year'].isnull().sum()

0

In [81]:
#ens_clean['IntEventDate'].isnull().sum()

0

In [48]:
(ens_clean['Year'] == "NaT").sum()

43

In [49]:
(ens_clean['EventDate'] == "NaT").sum()

0

In [50]:
#looking for where NaT exists in my IntEventDate created column because it matches where it is in EventDate column
nullintdate = (ens_clean['Year'] == "NaT")
ens_clean[nullintdate].head(44)

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
7100,6804,CALLAWAY,NaT,NaT,UNIT AT 80%. RECEIVED ISOLATION OF S/G BLOWDOW...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10 00:00:00.000,CALLAWAY,NaT
48045,49168,BRUNSWICK,NaT,2013-07-02 10:10:00,INVALID ACTUATION OF EMERGENCY DIESEL GENERATO...,100.0,24.0,0.0,100.0,24.0,0.0,2018-06-13 12:25:01.010,BRUNSWICK 1,NaT
48046,49169,PALO VERDE,NaT,2013-07-03 00:24:00,NOTICE OF UNUSUAL EVENT DUE TO EXPLOSION IN A ...,61.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.010,PALO VERDE 1,NaT
48047,49170,COOK,NaT,2013-07-03 01:15:00,UNAVAILABILITY OF TECHNICAL SUPPORT CENTER VEN...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.023,D.C. COOK 1,NaT
48048,49171,INDIAN POINT,NaT,2013-07-03 10:46:00,REACTOR TRIP FOLLOWING LOSS OF INSTRUMENT AIR ...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.023,INDIAN POINT 2,NaT
48049,49172,MILLSTONE,NaT,2013-07-03 11:37:00,STACK RADIATION MONITOR PRE-PLANNED MAINTENANC...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.023,MILLSTONE 2,NaT
48050,49173,DIABLO CANYON,NaT,2013-07-03 12:51:00,LOSS OF EMERGENCY RESPONSE COMMUNICATIONS DUE ...,73.0,100.0,0.0,48.0,100.0,0.0,2018-06-13 12:25:01.023,DIABLO CANYON 1,NaT
48051,49174,LASALLE,NaT,2013-07-05 12:34:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.040,LASALLE 1,NaT
48053,49176,NINE MILE POINT,NaT,2013-07-07 06:49:00,LOSS OF RADWASTE/REACTOR BUILDING VENT GASEOUS...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.040,NINE MILE POINT 2,NaT
48054,49177,GINNA,NaT,2013-07-07 11:15:00,LOSS OF EMERGENCY SIRENS DUE TO POWER OUTAGES\...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.057,GINNA,NaT
48055,49178,SAINT LUCIE,NaT,2013-07-08 10:57:00,OFFSITE NOTIFICATION DUE TO SODIUM HYPOCHLORIT...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.057,SAINT LUCIE 1,NaT
48056,49179,FITZPATRICK,NaT,2013-07-08 14:11:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.057,FITZPATRICK,NaT
48058,49181,MONTICELLO,NaT,2013-07-08 21:14:00,OFFSITE NOTIFICATION DUE TO SODIUM HYPOCHLORIT...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:01.070,MONTICELLO,NaT
48060,49183,MILLSTONE,NaT,2013-07-10 12:46:00,LOSS OF ASSESSMENT CAPABILITY DUE TO FAILURE O...,0.0,0.0,100.0,0.0,0.0,100.0,2018-06-13 12:25:01.070,MILLSTONE 3,NaT
48061,49184,DIABLO CANYON,NaT,2013-07-10 16:13:00,"UNIT 2 AUTOMATIC REACTOR TRIP \r\n\r\n""On July...",0.0,0.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.070,DIABLO CANYON 2,NaT
48063,49186,VOGTLE,NaT,2013-07-11 15:26:00,PLANT EMPLOYEE TRANSPORTED OFFSITE FOR MEDICAL...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.087,VOGTLE 1,NaT
48064,49187,PILGRIM,NaT,2013-07-11 19:49:00,FITNESS-FOR-DUTY REPORT INVOLVING A NON-LICENS...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.087,PILGRIM 1,NaT
48066,49189,PILGRIM,NaT,2013-07-15 00:58:00,UNUSUAL EVENT DECLARED DUE TO LOSS OF CONTROL ...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.103,PILGRIM 1,NaT
48067,49190,MILLSTONE,NaT,2013-07-15 10:44:00,LOSS OF ASSESSMENT CAPABILITY DUE TO PREPLANNE...,0.0,0.0,100.0,0.0,0.0,100.0,2018-06-13 12:25:01.103,MILLSTONE 3,NaT
48068,49191,COOK,NaT,2013-07-15 16:10:00,UNPLANNED LOSS OF COMMUNICATIONS DUE TO OFFSIT...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.103,D.C. COOK 1,NaT
48072,49195,CATAWBA,NaT,2013-07-16 14:20:00,60 DAY REPORT - INVALID ACTUATION OF SPECIFIED...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.117,CATAWBA 1,NaT
48073,49196,PILGRIM,NaT,2013-07-16 23:50:00,SALT SERVICE WATER SYSTEM DECLARED INOPERABLE\...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.133,PILGRIM 1,NaT
48190,49142,SAINT LUCIE,NaT,2013-06-23 20:39:00,TECHNICAL SUPPORT CENTER UNAVAILABLE DUE TO PR...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:00.917,SAINT LUCIE 1,NaT
48192,49144,VOGTLE,NaT,2013-06-24 04:49:00,PLANNED MAINTENANCE ON THE TECHNICAL SUPPORT C...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:00.917,VOGTLE 1,NaT
48198,49150,HARRIS,NaT,2013-06-27 04:46:00,TECHNICAL SUPPORT CENTER VENTILATION PLANNED M...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.917,HARRIS 1,NaT
48199,49151,DUANE ARNOLD,NaT,2013-06-27 11:33:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.930,DUANE ARNOLD,NaT
48200,49152,COLUMBIA,NaT,2013-06-28 04:07:00,HIGH PRESSURE CORE SPRAY AND DIVISION 3 DIESEL...,65.0,0.0,0.0,65.0,0.0,0.0,2018-06-13 12:25:00.930,COLUMBIA GENERATING STATION,NaT
48201,49153,DRESDEN,NaT,2013-06-28 14:18:00,DOOR INTERLOCK MALFUNCTION RESULTED IN BRIEF L...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.930,DRESDEN 2,NaT
48202,49154,WATTS BAR,NaT,2013-06-28 16:34:00,AUTOMATIC REACTOR TRIP DUE TO OFFSITE ELECTRIC...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.930,WATTS BAR 1,NaT
48205,49157,MCGUIRE,NaT,2013-06-29 03:12:00,OFFSITE NOTIFICATION TO NORTH CAROLINA - RAIN ...,100.0,37.0,0.0,100.0,37.0,0.0,2018-06-13 12:25:00.947,MCGUIRE 1,NaT
48206,49158,BEAVER VALLEY,NaT,2013-06-29 18:30:00,DIGITAL RADIATION MONITORING SYSTEM OPERATING ...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.947,BEAVER VALLEY 2,NaT
48207,49159,DAVIS BESSE,NaT,2013-06-29 22:48:00,AUTOMATIC REACTOR TRIP DUE TO REACTOR COOLANT ...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,DAVIS-BESSE,NaT
48210,49162,HOPE CREEK,NaT,2013-07-01 11:38:00,FUEL OIL SPILL INTO A STORM DRAIN LEADING TO T...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,HOPE CREEK 1,NaT
48211,49163,DAVIS BESSE,NaT,2013-07-01 15:27:00,DEGRADED CONDITION DUE TO RCP SEAL LINE PRESSU...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:00.977,DAVIS-BESSE,NaT
48331,48239,SURRY,NaT,2012-08-28 10:11:00,DISCOVERY OF AFTER-THE-FACT EMERGENCY CONDITIO...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.883,SURRY 2,NaT
48461,49128,PRAIRIE ISLAND,NaT,2013-06-17 18:34:00,POTENTIAL UNANALYZED CONDITION - CARBON DIOXID...,100.0,82.0,0.0,100.0,82.0,0.0,2018-06-13 12:25:00.917,PRAIRIE ISLAND 1,NaT
49146,49039,MILLSTONE,NaT,2013-05-16 10:20:00,MANUAL REACTOR TRIP DURING CONTROL ROD TESTING...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:00.900,MILLSTONE 3,NaT
49150,49043,NINE MILE POINT,NaT,2013-05-16 16:46:00,PRIMARY CONTAINMENT AIRLOCK NON-FUNCTIONAL DUE...,23.0,0.0,0.0,23.0,0.0,0.0,2018-06-13 12:25:00.900,NINE MILE POINT 1,NaT
53352,49161,CATAWBA,NaT,2013-06-30 22:53:00,<br><br>EN Revision Imported Date : 6/13/2018<...,94.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,CATAWBA 1,NaT
53353,49167,LASALLE,NaT,2013-07-01 21:47:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.993,LASALLE 2,NaT
53355,49188,DRESDEN,NaT,2013-07-14 16:29:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,100.0,100.0,0.0,100.0,100.0,2018-06-13 12:25:01.087,DRESDEN 2,NaT
53356,49193,COLUMBIA,NaT,2013-07-16 07:48:00,<br><br>EN Revision Imported Date : 6/13/2018<...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.117,COLUMBIA GENERATING STATION,NaT
53357,49197,ARKANSAS NUCLEAR ONE,NaT,2013-07-19 12:16:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:01.133,ARKANSAS NUCLEAR 1,NaT

In [51]:
#assigning the notification date to the event date where there is no value for event date
ens_clean.loc[nullintdate, "EventDate"] = ens_clean.loc[nullintdate, "NotificationDate"]

C:\Users\CEN1\Anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [52]:
ens_clean[nullintdate].head(44)

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
7100,6804,CALLAWAY,NaT,NaT,UNIT AT 80%. RECEIVED ISOLATION OF S/G BLOWDOW...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10 00:00:00.000,CALLAWAY,NaT
48045,49168,BRUNSWICK,2013-07-02 10:10:00,2013-07-02 10:10:00,INVALID ACTUATION OF EMERGENCY DIESEL GENERATO...,100.0,24.0,0.0,100.0,24.0,0.0,2018-06-13 12:25:01.010,BRUNSWICK 1,NaT
48046,49169,PALO VERDE,2013-07-03 00:24:00,2013-07-03 00:24:00,NOTICE OF UNUSUAL EVENT DUE TO EXPLOSION IN A ...,61.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.010,PALO VERDE 1,NaT
48047,49170,COOK,2013-07-03 01:15:00,2013-07-03 01:15:00,UNAVAILABILITY OF TECHNICAL SUPPORT CENTER VEN...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.023,D.C. COOK 1,NaT
48048,49171,INDIAN POINT,2013-07-03 10:46:00,2013-07-03 10:46:00,REACTOR TRIP FOLLOWING LOSS OF INSTRUMENT AIR ...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.023,INDIAN POINT 2,NaT
48049,49172,MILLSTONE,2013-07-03 11:37:00,2013-07-03 11:37:00,STACK RADIATION MONITOR PRE-PLANNED MAINTENANC...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.023,MILLSTONE 2,NaT
48050,49173,DIABLO CANYON,2013-07-03 12:51:00,2013-07-03 12:51:00,LOSS OF EMERGENCY RESPONSE COMMUNICATIONS DUE ...,73.0,100.0,0.0,48.0,100.0,0.0,2018-06-13 12:25:01.023,DIABLO CANYON 1,NaT
48051,49174,LASALLE,2013-07-05 12:34:00,2013-07-05 12:34:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.040,LASALLE 1,NaT
48053,49176,NINE MILE POINT,2013-07-07 06:49:00,2013-07-07 06:49:00,LOSS OF RADWASTE/REACTOR BUILDING VENT GASEOUS...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.040,NINE MILE POINT 2,NaT
48054,49177,GINNA,2013-07-07 11:15:00,2013-07-07 11:15:00,LOSS OF EMERGENCY SIRENS DUE TO POWER OUTAGES\...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.057,GINNA,NaT
48055,49178,SAINT LUCIE,2013-07-08 10:57:00,2013-07-08 10:57:00,OFFSITE NOTIFICATION DUE TO SODIUM HYPOCHLORIT...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.057,SAINT LUCIE 1,NaT
48056,49179,FITZPATRICK,2013-07-08 14:11:00,2013-07-08 14:11:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.057,FITZPATRICK,NaT
48058,49181,MONTICELLO,2013-07-08 21:14:00,2013-07-08 21:14:00,OFFSITE NOTIFICATION DUE TO SODIUM HYPOCHLORIT...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:01.070,MONTICELLO,NaT
48060,49183,MILLSTONE,2013-07-10 12:46:00,2013-07-10 12:46:00,LOSS OF ASSESSMENT CAPABILITY DUE TO FAILURE O...,0.0,0.0,100.0,0.0,0.0,100.0,2018-06-13 12:25:01.070,MILLSTONE 3,NaT
48061,49184,DIABLO CANYON,2013-07-10 16:13:00,2013-07-10 16:13:00,"UNIT 2 AUTOMATIC REACTOR TRIP \r\n\r\n""On July...",0.0,0.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:01.070,DIABLO CANYON 2,NaT
48063,49186,VOGTLE,2013-07-11 15:26:00,2013-07-11 15:26:00,PLANT EMPLOYEE TRANSPORTED OFFSITE FOR MEDICAL...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.087,VOGTLE 1,NaT
48064,49187,PILGRIM,2013-07-11 19:49:00,2013-07-11 19:49:00,FITNESS-FOR-DUTY REPORT INVOLVING A NON-LICENS...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.087,PILGRIM 1,NaT
48066,49189,PILGRIM,2013-07-15 00:58:00,2013-07-15 00:58:00,UNUSUAL EVENT DECLARED DUE TO LOSS OF CONTROL ...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.103,PILGRIM 1,NaT
48067,49190,MILLSTONE,2013-07-15 10:44:00,2013-07-15 10:44:00,LOSS OF ASSESSMENT CAPABILITY DUE TO PREPLANNE...,0.0,0.0,100.0,0.0,0.0,100.0,2018-06-13 12:25:01.103,MILLSTONE 3,NaT
48068,49191,COOK,2013-07-15 16:10:00,2013-07-15 16:10:00,UNPLANNED LOSS OF COMMUNICATIONS DUE TO OFFSIT...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.103,D.C. COOK 1,NaT
48072,49195,CATAWBA,2013-07-16 14:20:00,2013-07-16 14:20:00,60 DAY REPORT - INVALID ACTUATION OF SPECIFIED...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:01.117,CATAWBA 1,NaT
48073,49196,PILGRIM,2013-07-16 23:50:00,2013-07-16 23:50:00,SALT SERVICE WATER SYSTEM DECLARED INOPERABLE\...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.133,PILGRIM 1,NaT
48190,49142,SAINT LUCIE,2013-06-23 20:39:00,2013-06-23 20:39:00,TECHNICAL SUPPORT CENTER UNAVAILABLE DUE TO PR...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:00.917,SAINT LUCIE 1,NaT
48192,49144,VOGTLE,2013-06-24 04:49:00,2013-06-24 04:49:00,PLANNED MAINTENANCE ON THE TECHNICAL SUPPORT C...,100.0,100.0,0.0,100.0,100.0,0.0,2018-06-13 12:25:00.917,VOGTLE 1,NaT
48198,49150,HARRIS,2013-06-27 04:46:00,2013-06-27 04:46:00,TECHNICAL SUPPORT CENTER VENTILATION PLANNED M...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.917,HARRIS 1,NaT
48199,49151,DUANE ARNOLD,2013-06-27 11:33:00,2013-06-27 11:33:00,60 DAY OPTIONAL TELEPHONIC NOTIFICATION OF INV...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.930,DUANE ARNOLD,NaT
48200,49152,COLUMBIA,2013-06-28 04:07:00,2013-06-28 04:07:00,HIGH PRESSURE CORE SPRAY AND DIVISION 3 DIESEL...,65.0,0.0,0.0,65.0,0.0,0.0,2018-06-13 12:25:00.930,COLUMBIA GENERATING STATION,NaT
48201,49153,DRESDEN,2013-06-28 14:18:00,2013-06-28 14:18:00,DOOR INTERLOCK MALFUNCTION RESULTED IN BRIEF L...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.930,DRESDEN 2,NaT
48202,49154,WATTS BAR,2013-06-28 16:34:00,2013-06-28 16:34:00,AUTOMATIC REACTOR TRIP DUE TO OFFSITE ELECTRIC...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.930,WATTS BAR 1,NaT
48205,49157,MCGUIRE,2013-06-29 03:12:00,2013-06-29 03:12:00,OFFSITE NOTIFICATION TO NORTH CAROLINA - RAIN ...,100.0,37.0,0.0,100.0,37.0,0.0,2018-06-13 12:25:00.947,MCGUIRE 1,NaT
48206,49158,BEAVER VALLEY,2013-06-29 18:30:00,2013-06-29 18:30:00,DIGITAL RADIATION MONITORING SYSTEM OPERATING ...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.947,BEAVER VALLEY 2,NaT
48207,49159,DAVIS BESSE,2013-06-29 22:48:00,2013-06-29 22:48:00,AUTOMATIC REACTOR TRIP DUE TO REACTOR COOLANT ...,0.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,DAVIS-BESSE,NaT
48210,49162,HOPE CREEK,2013-07-01 11:38:00,2013-07-01 11:38:00,FUEL OIL SPILL INTO A STORM DRAIN LEADING TO T...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,HOPE CREEK 1,NaT
48211,49163,DAVIS BESSE,2013-07-01 15:27:00,2013-07-01 15:27:00,DEGRADED CONDITION DUE TO RCP SEAL LINE PRESSU...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:00.977,DAVIS-BESSE,NaT
48331,48239,SURRY,2012-08-28 10:11:00,2012-08-28 10:11:00,DISCOVERY OF AFTER-THE-FACT EMERGENCY CONDITIO...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.883,SURRY 2,NaT
48461,49128,PRAIRIE ISLAND,2013-06-17 18:34:00,2013-06-17 18:34:00,POTENTIAL UNANALYZED CONDITION - CARBON DIOXID...,100.0,82.0,0.0,100.0,82.0,0.0,2018-06-13 12:25:00.917,PRAIRIE ISLAND 1,NaT
49146,49039,MILLSTONE,2013-05-16 10:20:00,2013-05-16 10:20:00,MANUAL REACTOR TRIP DURING CONTROL ROD TESTING...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:00.900,MILLSTONE 3,NaT
49150,49043,NINE MILE POINT,2013-05-16 16:46:00,2013-05-16 16:46:00,PRIMARY CONTAINMENT AIRLOCK NON-FUNCTIONAL DUE...,23.0,0.0,0.0,23.0,0.0,0.0,2018-06-13 12:25:00.900,NINE MILE POINT 1,NaT
53352,49161,CATAWBA,2013-06-30 22:53:00,2013-06-30 22:53:00,<br><br>EN Revision Imported Date : 6/13/2018<...,94.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:00.963,CATAWBA 1,NaT
53353,49167,LASALLE,2013-07-01 21:47:00,2013-07-01 21:47:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,100.0,0.0,0.0,100.0,0.0,2018-06-13 12:25:00.993,LASALLE 2,NaT
53355,49188,DRESDEN,2013-07-14 16:29:00,2013-07-14 16:29:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,100.0,100.0,0.0,100.0,100.0,2018-06-13 12:25:01.087,DRESDEN 2,NaT
53356,49193,COLUMBIA,2013-07-16 07:48:00,2013-07-16 07:48:00,<br><br>EN Revision Imported Date : 6/13/2018<...,100.0,0.0,0.0,100.0,0.0,0.0,2018-06-13 12:25:01.117,COLUMBIA GENERATING STATION,NaT
53357,49197,ARKANSAS NUCLEAR ONE,2013-07-19 12:16:00,2013-07-19 12:16:00,<br><br>EN Revision Imported Date : 6/13/2018<...,0.0,0.0,0.0,0.0,0.0,0.0,2018-06-13 12:25:01.133,ARKANSAS NUCLEAR 1,NaT

In [53]:
#there are 10 rows where the notification date and event date do not match. manually fixing them here
ens_clean.loc[48045, "EventDate"] = "2013-05-07"
ens_clean.loc[48051, "EventDate"] = "2013-05-22"#48051,49174
ens_clean.loc[48056, "EventDate"] = "2013-05-10"#48056,49179
ens_clean.loc[48072, "EventDate"] = "2013-05-28"#48072,49195
ens_clean.loc[48199, "EventDate"] = "2013-05-02"#48199,49151
ens_clean.loc[53357, "EventDate"] = "2013-07-16"#53357,49197, rev
ens_clean.loc[7100, "EventDate"] = "1986-11-05" #7100,6804 missing both event date and notification date

C:\Users\CEN1\Anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [54]:
#checking one to make sure it worked
ens_clean.loc[48072]

EventNotificationNumber                                                49195
SiteName                                                             CATAWBA
EventDate                                                         2013-05-28
NotificationDate                                         2013-07-16 14:20:00
Text                       60 DAY REPORT - INVALID ACTUATION OF SPECIFIED...
CurrPower1                                                               100
CurrPower2                                                               100
CurrPower3                                                                 0
InitPower1                                                               100
InitPower2                                                               100
InitPower3                                                                 0
ImportedDate                                      2018-06-13 12:25:01.117000
NameAgain                                                          CATAWBA 1
Year                                                                     NaT
Name: 48072, dtype: object

In [56]:
ens_clean.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
18701,18716,FORT CALHOUN,1990-06-15 18:24:00,1990-06-15 18:24:00,LICENSEE PLANS TO DISABLE THE CONTROL ROOM ENS...,94.0,0.0,0.0,94.0,0.0,0.0,2003-04-10,FORT CALHOUN,1990-06-15
18702,18717,PALISADES,1990-06-15 20:10:00,1990-06-15 22:49:00,THE UNIT EXPERIENCED A REACTOR PROTECTION SYST...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,PALISADES,1990-06-15
18704,18719,NORTH ANNA,1990-06-16 14:53:00,1990-06-16 18:47:00,LICENSEE DISCOVERED THAT THE SEISMIC SUPPORTS ...,100.0,100.0,0.0,100.0,100.0,0.0,2003-04-10,NORTH ANNA 1,1990-06-16
18705,18720,MILLSTONE,1990-06-17 01:18:00,1990-06-17 02:25:00,"CHANGING INDICATOR LIGHT ON ""B"" EDG LOAD SEQUE...",0.0,89.0,0.0,0.0,89.0,0.0,2003-04-10,MILLSTONE 2,1990-06-17
18706,18721,QUAD CITIES,1990-06-17 03:13:00,1990-06-17 04:48:00,SAFEGUARDS DEGRADATION DUE TO LOSS OF SECURITY...,98.0,99.0,0.0,98.0,99.0,0.0,2003-04-10,QUAD CITIES 1,1990-06-17

In [57]:
#checking the EventDate column again for null-type values because above it shows some NaT values
(ens_clean['EventDate'] == "NaT").sum()

0

In [58]:
ens_clean['Year'] = ens_clean['EventDate'].astype(str).str[:10]

C:\Users\CEN1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
#ens_clean_pow['IntEventDate'] = ens_clean_pow['Year'].str.replace("-","")

In [ ]:
#(ens_clean_pow['IntEventDate'] == "NaT").sum()

In [59]:
(ens_clean['Year'] == "NaT").sum()

0

In [60]:
ens_clean.dtypes

EventNotificationNumber             int64
SiteName                           object
EventDate                          object
NotificationDate           datetime64[ns]
Text                               object
CurrPower1                        float64
CurrPower2                        float64
CurrPower3                        float64
InitPower1                        float64
InitPower2                        float64
InitPower3                        float64
ImportedDate               datetime64[ns]
NameAgain                          object
Year                               object
dtype: object

In [75]:
ens_clean['Year'].astype(np.datetime64)

EventNotificationId
18701   1990-06-15
18702   1990-06-15
18704   1990-06-16
18705   1990-06-17
18706   1990-06-17
           ...
18695   1990-06-14
18696   1990-03-26
18697   1990-06-14
18698   1990-06-15
18699   1990-06-15
Name: Year, Length: 39081, dtype: datetime64[ns]

In [76]:
ens_clean.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
18701,18716,FORT CALHOUN,1990-06-15 18:24:00,1990-06-15 18:24:00,LICENSEE PLANS TO DISABLE THE CONTROL ROOM ENS...,94.0,0.0,0.0,94.0,0.0,0.0,2003-04-10,FORT CALHOUN,1990-06-15
18702,18717,PALISADES,1990-06-15 20:10:00,1990-06-15 22:49:00,THE UNIT EXPERIENCED A REACTOR PROTECTION SYST...,0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,PALISADES,1990-06-15
18704,18719,NORTH ANNA,1990-06-16 14:53:00,1990-06-16 18:47:00,LICENSEE DISCOVERED THAT THE SEISMIC SUPPORTS ...,100.0,100.0,0.0,100.0,100.0,0.0,2003-04-10,NORTH ANNA 1,1990-06-16
18705,18720,MILLSTONE,1990-06-17 01:18:00,1990-06-17 02:25:00,"CHANGING INDICATOR LIGHT ON ""B"" EDG LOAD SEQUE...",0.0,89.0,0.0,0.0,89.0,0.0,2003-04-10,MILLSTONE 2,1990-06-17
18706,18721,QUAD CITIES,1990-06-17 03:13:00,1990-06-17 04:48:00,SAFEGUARDS DEGRADATION DUE TO LOSS OF SECURITY...,98.0,99.0,0.0,98.0,99.0,0.0,2003-04-10,QUAD CITIES 1,1990-06-17

In [77]:
ens_clean.columns

Index(['EventNotificationNumber', 'SiteName', 'EventDate', 'NotificationDate',
       'Text', 'CurrPower1', 'CurrPower2', 'CurrPower3', 'InitPower1',
       'InitPower2', 'InitPower3', 'ImportedDate', 'NameAgain', 'Year'],
      dtype='object')

In [78]:
#making sure there are no null values
ens_clean['EventNotificationNumber'].isnull().sum()

0

In [79]:
#making sure there are no duplicate entries
ens_clean['EventNotificationNumber'].duplicated().sum()

0

In [80]:
#checking for how many null values in the column. Some are ok and make sense.
ens_clean['CurrPower1'].isnull().sum()

13

In [81]:
ens_clean['CurrPower2'].isnull().sum()

20

In [82]:
ens_clean['CurrPower3'].isnull().sum()

24

In [83]:
ens_clean.shape

(39081, 14)

In [96]:
#I only want data from 2002 to July 1, 2020
ens_clean_dates = ens_clean.loc[ens_clean['Year'] >= '2002-01-01']
ens_clean_dates = ens_clean_dates.loc[ens_clean_dates['Year'] <= '2020-06-30']

In [97]:
ens_clean_dates.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
37561,38782,POINT BEACH,2002-03-19 10:56:00,2002-03-19 14:15:00,LOSS OF SPDS DEGRADES COMMUNICATION/ASSESSMENT...,0.0,98.0,0.0,0.0,100.0,0.0,2003-04-10,POINT BEACH 2,2002-03-19
37563,38784,PALO VERDE,2002-03-15 06:30:00,2002-03-19 19:02:00,NON WORK RELATED FATALITY NOTIFICATION IN ACCO...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,PALO VERDE 1,2002-03-15
37567,38788,RIVER BEND,2002-03-20 12:30:00,2002-03-20 14:27:00,EMERGENCY DIESEL GENERATOR TURBOCHARGER FIRE\r...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,RIVER BEND 1,2002-03-20
37568,38790,LIMERICK,2002-03-20 15:43:00,2002-03-20 22:56:00,UNIT-1 HPCI SYSTEM FAILED TO MEET REQUIRED RES...,2.0,0.0,0.0,2.0,0.0,0.0,2003-04-10,LIMERICK 1,2002-03-20
37569,38791,NINE MILE POINT,2002-03-21 03:13:00,2002-03-21 10:11:00,"RPS LOGIC ACTUATION WHILE SHUTDOWN\r\n\r\n""At ...",0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,NINE MILE POINT 2,2002-03-21

In [98]:
ens_clean_dates.shape

(8732, 14)

In [99]:
ens_clean_dates.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
37561,38782,POINT BEACH,2002-03-19 10:56:00,2002-03-19 14:15:00,LOSS OF SPDS DEGRADES COMMUNICATION/ASSESSMENT...,0.0,98.0,0.0,0.0,100.0,0.0,2003-04-10,POINT BEACH 2,2002-03-19
37563,38784,PALO VERDE,2002-03-15 06:30:00,2002-03-19 19:02:00,NON WORK RELATED FATALITY NOTIFICATION IN ACCO...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,PALO VERDE 1,2002-03-15
37567,38788,RIVER BEND,2002-03-20 12:30:00,2002-03-20 14:27:00,EMERGENCY DIESEL GENERATOR TURBOCHARGER FIRE\r...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,RIVER BEND 1,2002-03-20
37568,38790,LIMERICK,2002-03-20 15:43:00,2002-03-20 22:56:00,UNIT-1 HPCI SYSTEM FAILED TO MEET REQUIRED RES...,2.0,0.0,0.0,2.0,0.0,0.0,2003-04-10,LIMERICK 1,2002-03-20
37569,38791,NINE MILE POINT,2002-03-21 03:13:00,2002-03-21 10:11:00,"RPS LOGIC ACTUATION WHILE SHUTDOWN\r\n\r\n""At ...",0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,NINE MILE POINT 2,2002-03-21

In [100]:
ens_clean_dates.tail()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
54941,54752,CATAWBA,2020-06-21 21:00:00,2020-06-22 01:00:00,UNPLANNED TECHNICAL SUPPORT CENTER VENTILATION...,100.0,100.0,0.0,100.0,100.0,0.0,2020-07-21 05:35:00.167,CATAWBA 1,2020-06-21
54943,54753,WATTS BAR,2020-06-22 13:04:00,2020-06-22 13:45:00,OFFSITE NOTIFICATION - GROUNDWATER INITIATIVE...,100.0,100.0,0.0,100.0,100.0,0.0,2020-07-21 05:35:00.167,WATTS BAR 1,2020-06-22
54960,54738,MILLSTONE,2020-06-05 03:20:00,2020-06-05 10:39:00,<br><br>EN Revision Imported Date : 10/6/2020<...,0.0,0.0,0.0,0.0,0.0,0.0,2020-10-06 05:26:00.817,MILLSTONE 2,2020-06-05
55018,54820,PEACH BOTTOM,2020-06-08 04:24:00,2020-08-06 13:10:00,"INVALID SPECIFIED SYSTEM ACTUATION\r\n\r\n""Thi...",0.0,100.0,0.0,0.0,100.0,0.0,2020-08-07 05:10:01.043,PEACH BOTTOM 3,2020-06-08
55072,54874,NINE MILE POINT,2020-03-06 00:00:00,2020-09-01 14:48:00,PART 21 REPORT - FAILURE OF MAIN STEAM ISOLATI...,0.0,0.0,0.0,0.0,0.0,0.0,2020-09-02 04:45:01.090,NINE MILE POINT 2,2020-03-06

In [101]:
ens_clean_dates.sort_values(by=['Year'])

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year
EventNotificationId,,,,,,,,,,,,,,
39193,38602,CRYSTAL RIVER,2002-01-01 09:19:00,2002-01-01 10:08:00,OFFSITE NOTIFICATION DUE RESCUED SEA TURTLE\r\...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10 00:00:00.000,CRYSTAL RIVER 3,2002-01-01
39192,38601,COOPER,2002-01-01 00:42:00,2002-01-01 09:41:00,HIGH PRESSURE COOLANT INJECTION (HPCI) TURBINE...,10.0,0.0,0.0,10.0,0.0,0.0,2003-04-10 00:00:00.000,COOPER,2002-01-01
39196,38605,DAVIS BESSE,2002-01-02 01:50:00,2002-01-02 09:48:00,SAFETY PARAMETER DISPLAY SYSTEM (SPDS) IS OUT ...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10 00:00:00.000,DAVIS-BESSE,2002-01-02
39198,38607,WOLF CREEK,2002-01-02 12:30:00,2002-01-02 21:34:00,LOSS OF SAFETY PARAMETER DISPLAY SYSTEM (SPDS)...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10 00:00:00.000,WOLF CREEK 1,2002-01-02
39195,38604,HARRIS,2002-01-02 03:05:00,2002-01-02 04:56:00,MANUAL REACTOR TRIP DUE TO DECREASING STEAM GE...,0.0,0.0,0.0,7.0,0.0,0.0,2003-04-10 00:00:00.000,HARRIS 1,2002-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55018,54820,PEACH BOTTOM,2020-06-08 04:24:00,2020-08-06 13:10:00,"INVALID SPECIFIED SYSTEM ACTUATION\r\n\r\n""Thi...",0.0,100.0,0.0,0.0,100.0,0.0,2020-08-07 05:10:01.043,PEACH BOTTOM 3,2020-06-08
54929,54742,SUMMER,2020-06-08 13:55:00,2020-06-08 18:52:00,OFFSITE NOTIFICATION - TRANSMISSION FLUID SPIL...,100.0,0.0,0.0,100.0,0.0,0.0,2020-07-07 04:40:00.370,SUMMER,2020-06-08
54938,54749,BEAVER VALLEY,2020-06-18 17:25:00,2020-06-18 20:37:00,NOTIFICATION OF ENVIRONMENTAL REPORT TO ANOTHE...,100.0,0.0,0.0,100.0,0.0,0.0,2020-07-17 04:45:00.430,BEAVER VALLEY 1,2020-06-18
54941,54752,CATAWBA,2020-06-21 21:00:00,2020-06-22 01:00:00,UNPLANNED TECHNICAL SUPPORT CENTER VENTILATION...,100.0,100.0,0.0,100.0,100.0,0.0,2020-07-21 05:35:00.167,CATAWBA 1,2020-06-21
54943,54753,WATTS BAR,2020-06-22 13:04:00,2020-06-22 13:45:00,OFFSITE NOTIFICATION - GROUNDWATER INITIATIVE...,100.0,100.0,0.0,100.0,100.0,0.0,2020-07-21 05:35:00.167,WATTS BAR 1,2020-06-22

In [102]:
ens_clean_dates['Quarter'] = pd.PeriodIndex(pd.to_datetime(ens_clean_dates.Year), freq='Q')

In [103]:
ens_clean_dates.head()

,EventNotificationNumber,SiteName,EventDate,NotificationDate,Text,CurrPower1,CurrPower2,CurrPower3,InitPower1,InitPower2,InitPower3,ImportedDate,NameAgain,Year,Quarter
EventNotificationId,,,,,,,,,,,,,,,
37561,38782,POINT BEACH,2002-03-19 10:56:00,2002-03-19 14:15:00,LOSS OF SPDS DEGRADES COMMUNICATION/ASSESSMENT...,0.0,98.0,0.0,0.0,100.0,0.0,2003-04-10,POINT BEACH 2,2002-03-19,2002Q1
37563,38784,PALO VERDE,2002-03-15 06:30:00,2002-03-19 19:02:00,NON WORK RELATED FATALITY NOTIFICATION IN ACCO...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,PALO VERDE 1,2002-03-15,2002Q1
37567,38788,RIVER BEND,2002-03-20 12:30:00,2002-03-20 14:27:00,EMERGENCY DIESEL GENERATOR TURBOCHARGER FIRE\r...,100.0,0.0,0.0,100.0,0.0,0.0,2003-04-10,RIVER BEND 1,2002-03-20,2002Q1
37568,38790,LIMERICK,2002-03-20 15:43:00,2002-03-20 22:56:00,UNIT-1 HPCI SYSTEM FAILED TO MEET REQUIRED RES...,2.0,0.0,0.0,2.0,0.0,0.0,2003-04-10,LIMERICK 1,2002-03-20,2002Q1
37569,38791,NINE MILE POINT,2002-03-21 03:13:00,2002-03-21 10:11:00,"RPS LOGIC ACTUATION WHILE SHUTDOWN\r\n\r\n""At ...",0.0,0.0,0.0,0.0,0.0,0.0,2003-04-10,NINE MILE POINT 2,2002-03-21,2002Q1

In [105]:
en = ens_clean_dates[['Quarter', 'Year', 'NameAgain', 'EventNotificationNumber']]

In [106]:
en.shape

(8732, 4)

In [107]:
en.head()

,Quarter,Year,NameAgain,EventNotificationNumber
EventNotificationId,,,,
37561,2002Q1,2002-03-19,POINT BEACH 2,38782
37563,2002Q1,2002-03-15,PALO VERDE 1,38784
37567,2002Q1,2002-03-20,RIVER BEND 1,38788
37568,2002Q1,2002-03-20,LIMERICK 1,38790
37569,2002Q1,2002-03-21,NINE MILE POINT 2,38791

In [123]:
#ensclean = en.groupby(['Quarter', 'NameAgain']).count()['NameAgain']
ensclean = en.groupby(by=['Quarter', 'NameAgain']).agg(ENCount = pd.NamedAgg(column = "NameAgain", aggfunc ="count"))

In [124]:
ensclean.head()

                         ENCount
Quarter NameAgain
2002Q1  BEAVER VALLEY 1        1
        BEAVER VALLEY 2        1
        BROWNS FERRY 2         1
        BROWNS FERRY 3         2
        BRUNSWICK 2            1

In [125]:
ensclean.tail()

                       ENCount
Quarter NameAgain
2020Q2  SURRY 1              1
        SUSQUEHANNA 1        1
        WATERFORD 3          2
        WATTS BAR 1          2
        WATTS BAR 2          1

In [126]:
ensclean.shape

(4277, 1)

In [129]:
#create a new Excel file with just the cleaned up data we want
ensclean.to_excel('ENdata.xlsx')